version: '3.9'

services:
  backend:
    build: .
    container_name: youtube-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
  
  localstack:
    image: localstack/localstack
    container_name: youtube-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - ./localstack-data:/var/lib/localstack